Add attachmentId to RequestMetaData
cyface-de/serialization pull request #58
Opened 2024-06-04 15:43 UTC by hb0

2024-06-17 07:46 UTC, muthenberg requested changes
See my comments inline. I think some kind of abstraction is necessary to find the common ground between measurements and attachments handle both cleanly together, or if that is not possible, separate handling them.

2024-06-17 07:46 UTC, muthenberg commented on libs/model/src/main/kotlin/de/cyface/model/RequestMetaData.kt
> +    val attachmentIdentifier: String? = null,
That's a code smell. There should be a different way to handle this, with either delegation or inheritance.

2024-06-17 07:46 UTC, muthenberg commented on libs/model/src/main/kotlin/de/cyface/model/RequestMetaData.kt
> +            "Field attachmentId had an invalid length of ${attachmentIdentifier!!.length.toLong()}"
This is going to crash hard if attachmentIdentifier is actually null. Using !! is also usually a Code smell.

2024-06-24 12:19 UTC, hb0 reviewed
Suggestion to fix the code smell

2024-06-24 12:19 UTC, hb0 commented on libs/model/src/main/java/de/cyface/model/MeasurementIdentifier.java
Was converted to Kotlin. I first wanted to reuse this Class. But I think it's better not to make the RequestMetaData and the Flink Pipeline which uses this Model dependent from each other.

2024-06-24 12:19 UTC, hb0 commented on libs/model/src/main/kotlin/de/cyface/model/RequestMetaData.kt
The Identifier type is now defined via the generic type of the identifier instead of having attachmentId nullable.

I also had to group the metadata thematically, or else detekt complains about too many parameters.

2024-06-24 12:19 UTC, hb0 commented on libs/model/src/main/kotlin/de/cyface/model/RequestMetaData.kt
> +        private const val serialVersionUID = 2L
increased as the RequestMetaData properties changed.

2024-06-24 12:19 UTC, hb0 commented on libs/model/src/main/kotlin/de/cyface/model/RequestMetaData.kt
>      }
Added as 2 RequestMetaData instances should only be different when the identifier is different, either deviceMeasurementId for a measurement upload or the deviceAttachementId for the attachment upload.

2024-07-10 11:04 UTC, hb0 commented on libs/model/src/main/kotlin/de/cyface/model/RequestMetaData.kt
**FIXME:** Remove this or undo this if still needed, but without generic type

2024-07-15 09:29 UTC, merged